{{- if .Values.esConfig }}
apiVersion: v1
kind: Secret
metadata:
  name: elastic-secrets
  labels:
    app: elasticsearch
    xpack: "true"
    production: "true"
type: Opaque
data:
  ELASTIC_USERNAME: <CHANGE-ME>
  ELASTIC_PASSWORD: <CHANGE-ME>
{{- end -}}